name: Continuous Deployment
on: [push]
jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up Just
        uses: taiki-e/install-action@just

      - name: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: call gcloud info
        run: gcloud info
