name: Continuous Integration
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up Go
        uses: actions/setup-go@v4

      - name: set up Just
        uses: taiki-e/install-action@just

      - name: call just test
        run: just test
